# 1차원 데이터
- 데이터 중심의 지표

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Jupyter 에서 출력의 소수점을 3자리로 제한
%precision 3

'%.3f'

In [3]:
pd.set_option("precision", 3)

In [4]:
df = pd.read_csv("./ch2_scores_em.csv", index_col="student number")

In [5]:
df.shape

(50, 2)

In [6]:
df.head(3)

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63

In [7]:
scores = np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [10]:
scores = df.loc[1:10, 'english'].to_numpy(dtype=np.float64)
scores

array([42., 69., 56., 41., 57., 48., 65., 49., 65., 58.])

In [13]:
scores = df.loc[1:10, 'english']
scores

student number
1     42
2     69
3     56
4     41
5     57
6     48
7     65
8     49
9     65
10    58
Name: english, dtype: int64

In [14]:
scores = df.iloc[1:10, 0]
scores

student number
2     69
3     56
4     41
5     57
6     48
7     65
8     49
9     65
10    58
Name: english, dtype: int64

In [15]:
# 평균
sum(scores)/len(scores)

56.444

In [16]:
np.mean(scores)

56.444

In [17]:
df['english'].mean()

58.380

In [18]:
# 중앙값
sorted_scores = np.sort(scores)
sorted_scores

array([41, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [20]:
n = len(sorted_scores)
if n % 2 == 0:
    m0 = sorted_scores[n//2-1]
    m1 = sorted_scores[n//2]
    median = (m0 + m1) / 2
else:
    median = sorted_scores[(n+1)//2-1]

In [21]:
median

57

In [22]:
np.median(scores)

57.0

In [23]:
df['english'].median()

57.500

In [24]:
# 최빈값
pd.Series([1, 1, 1, 2, 2, 3]).mode()

0    1
dtype: int64

# 데이터의 산포도 지표
- 분산과 표준편차

In [25]:
# 편차
mean = np.mean(scores)
deviation = scores - mean
deviation

student number
2     12.556
3     -0.444
4    -15.444
5      0.556
6     -8.444
7      8.556
8     -7.444
9      8.556
10     1.556
Name: english, dtype: float64

In [26]:
another_score = [50, 60, 58, 54, 51, 56, 57, 53, 52, 59]
another_mean = np.mean(another_score)
another_deviation = another_score - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [27]:
np.mean(deviation)

0.000

In [28]:
np.mean(another_deviation)

0.0

In [29]:
# 분산
np.mean(deviation ** 2)

74.691

In [30]:
np.var(deviation)

74.691

In [31]:
np.var(scores, ddof=0)

74.691

In [32]:
np.var(scores, ddof=1)

84.028

In [33]:
# 표준편차
np.sqrt(np.var(scores, ddof=0))

8.642416214502248

In [35]:
np.std(scores, ddof=0)

8.642

In [38]:
# 범위, 4분위수
np.max(scores) - np.min(scores)

28

In [39]:
scores_Q1 = np.percentile(scores, 25)
scores_Q3 = np.percentile(scores, 75)
scores_IQR = scores_Q3 - scores_Q1
scores_IQR

16.0