# 멀티 퍼셉트론 순방향 패스

In [1]:
import numpy as np

In [2]:
# 활성화 함수 : 시그모이드
def actf(x):
    return 1 / ( 1 + np.exp(-x))

In [3]:
# 시그모이드 함수의 미분치
def actf_deriv(x):
    return x * ( 1 - x)

In [4]:
# 입력유닛 개수, 은닉유닛 개수, 출력유닛 개수
inputs, hiddens, outputs = 2, 2, 1
learning_rate = 0.2

In [5]:
# 학습 샘플 과 정답 : XOR
X = np.array([[0,0], [0,1], [1,0], [1,1]])
T = np.array([[0], [1], [1], [0]])

# 훈련 데이터
W1 = np.array([[0.10, 0.20], [0.30, 0.40]])
W2 = np.array([[0.50], [0.60]])
B1 = np.array([0.1, 0.2])
B2 = np.array([0.3])

In [6]:
# 순방향 전파 계산
def predict(x):
    layer0 = x # 입력을 layer0에 대입
    Z1 = np.dot(layer0, W1) + B1 # 입력값에 대해 aiffine function계산 : 행렬곱 계산 한다.
    layer1 = actf(Z1) # 활성화 함수 (시그모이드) 계산
    Z2 = np.dot(layer1, W2) + B2 # layer1에 대해 aiffine function계산 : 행렬곱 계산 한다.
    layer2 = actf(Z2) # 활성화 함수 (시그모이드) 계산
    return layer0, layer1, layer2


In [9]:
def test():
    for x, y in zip(X, T):
        x = np.reshape(x, (1, -1))
        layer0 , layer1, layer2 = predict(x)
        print(x, y, layer2, actf_deriv(layer2))

In [10]:
test()

[[0 0]] [0] [[0.70938314]] [[0.2061587]]
[[0 1]] [1] [[0.72844306]] [[0.19781377]]
[[1 0]] [1] [[0.71791234]] [[0.20251421]]
[[1 1]] [0] [[0.73598705]] [[0.19431011]]
