# Affine Functions with 1 Feature

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [10]:
x = tf.constant([[10.]]) # Input setting (input -> matrix)
print(type(x))
dense = Dense(units=1, activation='linear') # imp. an affine function
#dense.get_weights() # error
y_tf = dense(x) # forward propagation + params initialization z = xw + b
W, b = dense.get_weights()
print(W, b, y_tf.numpy())

<class 'tensorflow.python.framework.ops.EagerTensor'>
[[-1.3742678]] [0.] [[-13.742678]]


In [14]:
print(type(W), type(b))
y_tf

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-13.742678]], dtype=float32)>

In [13]:
y_man = tf.linalg.matmul(x, W) + b

print('=======Input / Weight / Biase===========')
print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('W: {}\n{}\n'.format(W.shape, W))
print('b: {}\n{}\n'.format(b.shape, b))

print('===== output =======')
print('y(Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y(Manual): {}\n{}\n'.format(y_man.shape, y_man.numpy()))

=======Input / Weight / Biase===========
x: (1, 1)
[[10.]]

W: (1, 1)
[[-1.3742678]]

b: (1,)
[0.]

===== output =======
y(Tensorflow): (1, 1)
[[-13.742678]]

y(Manual): (1, 1)
[[-13.742678]]



In [17]:
# Params Intialzation
from tensorflow.keras.initializers import Constant
# weight / bias setting
W, b = (tf.constant(10.), tf.constant(20.))
w_init, b_init = Constant(10.), Constant(20.)

dense = Dense(units=1, activation='linear', 
              kernel_initializer=w_init, 
              bias_initializer=b_init)
y_tf = dense(x)
W, b = dense.get_weights()

print('W: {}\n{}\n'.format(W.shape, W))
print('b: {}\n{}\n'.format(b.shape, b))

W: (1, 1)
[[10.]]

b: (1,)
[20.]



In [19]:
print(y_tf.numpy()) # 10 * 10 + 20

[[120.]]


# Affine Functions with n Feature

In [20]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

tf.random.set_seed(10)
x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)
dense = Dense(units=1)

In [21]:
x.numpy()

array([[6.4415097 , 8.082472  , 8.976547  , 6.3689017 , 6.270969  ,
        9.936013  , 0.23594856, 0.36683917, 5.8605776 , 5.7403145 ]],
      dtype=float32)

In [22]:
y_tf = dense(x)
W, b = dense.get_weights()
y_man = tf.linalg.matmul(x, W) + b

In [23]:
print('=======Input / Weight / Biase===========')
print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('W: {}\n{}\n'.format(W.shape, W))
print('b: {}\n{}\n'.format(b.shape, b))

print('===== output =======')
print('y(Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y(Manual): {}\n{}\n'.format(y_man.shape, y_man.numpy()))

=======Input / Weight / Biase===========
x: (1, 10)
[[6.4415097  8.082472   8.976547   6.3689017  6.270969   9.936013
  0.23594856 0.36683917 5.8605776  5.7403145 ]]

W: (10, 1)
[[ 0.08091772]
 [-0.10844558]
 [-0.5296768 ]
 [ 0.30087596]
 [-0.18808389]
 [ 0.29202002]
 [-0.39361012]
 [ 0.09546101]
 [-0.4453573 ]
 [ 0.6689041 ]]

b: (1,)
[0.]

===== output =======
y(Tensorflow): (1, 1)
[[-0.29983306]]

y(Manual): (1, 1)
[[-0.29983306]]

