# Dense Layers
- 해당 Layer가 오기 직전의 Input과 후의 Output을 완전 연결 계층으로 만듬
- Dense Layer를 사용해 감소된 차원의 Feature Map들만 Input으로 해 Output과 완전연결 계층 생성해 효율적 학습 가능

## ✔ Dense Layer의 필요성
- Image가 고해상도인 경우 parameter가 급증
- Spatial Feature가 직렬화로 무시됌


In [ ]:
# Shape of Dense Layers
import tensorflow as tf
from tensorflow.keras.layers import Dense
import warnings
warnings.filterwarnings('ignore')

In [4]:
N, n_feature = 1, 10
tf.random.set_seed(10)
x = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
y = dense(x)

W, b = dense.get_weights()
print('===== Input / Weight / Bias =====')
print('x: ', x.shape)
print('W: ', W.shape)
print('b: ', b.shape)
print('y: ', y.shape)

===== Input / Weight / Bias =====
x:  (1, 10)
W:  (10, 3)
b:  (3,)
y:  (1, 3)


In [5]:
N, n_feature = 3, 10
tf.random.set_seed(10)
x = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
y = dense(x)

W, b = dense.get_weights()
print('===== Input / Weight / Bias =====')
print('x: ', x.shape)
print('W: ', W.shape)
print('b: ', b.shape)
print('y: ', y.shape)

===== Input / Weight / Bias =====
x:  (3, 10)
W:  (10, 3)
b:  (3,)
y:  (3, 3)


In [6]:
# Output Calculations
import numpy as np
N, n_feature = 4, 10
tf.random.set_seed(10)
x = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
y_tf = dense(x)
print('y(Tensorflow): \n', y_tf.numpy())

W, b = dense.get_weights()

# calculate with matrix multiplication
z = tf.linalg.matmul(x, W) + b
y_man = 1 / (1+tf.math.exp(-z))
print('y(with matrix multiplocation: \n)', y_man.numpy())

# calculate with dot products
y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
    x_ = x[x_idx]
    for nu_idx in range(n_neuron):
        w, b_ = W[:, nu_idx], b[nu_idx]
        z = tf.reduce_sum(x_ * w) + b_
        a = 1 / (1+np.exp(-z))
        y_man_vec[x_idx, nu_idx] = a
print('y(with dot product): \n', y_man_vec)

y(Tensorflow): 
 [[0.8874107  0.28992724 0.35931098]
 [0.7775674  0.6703928  0.20458944]
 [0.42813158 0.61795133 0.4594186 ]
 [0.8721554  0.18618418 0.49994683]]
y(with matrix multiplocation: 
) [[0.8874107  0.28992724 0.35931098]
 [0.7775674  0.6703928  0.20458944]
 [0.42813158 0.61795133 0.4594186 ]
 [0.8721554  0.18618418 0.49994683]]
ERROR! Session/line number was not unique in database. History logging moved to new session 582
y(with dot product): 
 [[0.8874107  0.28992724 0.35931102]
 [0.7775674  0.67039285 0.20458942]
 [0.4281316  0.61795133 0.45941861]
 [0.87215541 0.18618418 0.49994681]]


# Model Implementation

In [7]:
# Model Implementation with Sequential Method
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [8]:
model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

ERROR! Session/line number was not unique in database. History logging moved to new session 583


In [10]:
n_neurons = [3, 4, 5, 6]

model = list()
for n_neuron in n_neurons:
    model.append(Dense(units=n_neuron, activation='sigmoid'))
    
model = Sequential()
for n_neuron in n_neurons:
    model.add(Dense(units=n_neuron, activation='sigmoid'))
    
# 기본적으로 리스트나 시퀀셜을 사용하는 것은 비슷 
# Sequential class 이용 하면 부가 기능 지원

In [12]:
# Model Implementation with Model-subclassing
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

In [13]:
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__() # 상위 클래스 Model을 초기화 작업 호출
        self.dense1 = Dense(units=10, activation='sigmoid')
        self.dense2 = Dense(units=20, activation='sigmoid')

model = TestModel()
print(model.dense1)
print(model.dense2)

In [15]:
# Forward Propagation of Models
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential

ERROR! Session/line number was not unique in database. History logging moved to new session 585


In [17]:
tf.random.set_seed(10)
X = tf.random.normal(shape=(4, 10))

# sequential method
model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X) # 요 시점 W, b 초기화가 됨. (기본은 랜덤)
print(Y.numpy())

# Model-subclassing
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        self.dense1 = Dense(units=10, activation='sigmoid')
        self.dense2 = Dense(units=20, activation='sigmoid')

    def call(self, x):
        x = self.dense1(x)
        x = self.dense2(x)
        return x

model = TestModel()
Y = model(X) # 요 시점 W, b 초기화가 됨. (기본은 랜덤)
print(Y.numpy())

[[0.55650467 0.5736378  0.5630582  0.38230422 0.58008534 0.46750382
  0.5453265  0.57239604 0.577736   0.5092679  0.63902617 0.41740972
  0.49596012 0.48987812 0.3786818  0.6252993  0.507673   0.5675629
  0.44154426 0.5643339 ]
 [0.542635   0.5824134  0.55322725 0.4182083  0.45012072 0.46044162
  0.5349409  0.5653203  0.50379336 0.5493765  0.6248533  0.48017088
  0.4684742  0.448952   0.44587278 0.58404434 0.40546963 0.5525067
  0.48883933 0.53214234]
 [0.55147415 0.54305255 0.5955269  0.39230987 0.49052256 0.47776744
  0.5909605  0.6016277  0.5510731  0.53855234 0.6518259  0.36644483
  0.46875128 0.42796102 0.42704156 0.62905306 0.47941467 0.5476874
  0.45441562 0.5198266 ]
 [0.5501883  0.6035677  0.543347   0.37710547 0.553181   0.46198443
  0.5360454  0.57856405 0.59026885 0.4992652  0.66410637 0.46451893
  0.47575763 0.51785564 0.3944179  0.58145726 0.4373687  0.54021823
  0.46061313 0.6211433 ]]
[[0.4081323  0.42172372 0.41616654 0.6124194  0.5208273  0.4728814
  0.45194685 0.5506