# Activation Functions
- DeepLearning Network에서 Node에 들어오는 값들을 곧바로 다음 Layer로 전달하지 X
- => 비선형 함수를 통과 시켜 전달함!
<br>

</br>

### ✔ 비선형 함수를 이용하는 이유?
- 선형함수를 사용할 시에 층을 깊게 하는 의미가 줄어들기 때문

In [4]:
tf.__version__

'2.1.0'

In [7]:
import tensorflow as tf
# from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

In [14]:
tf.random.set_seed(10)
x = tf.random.normal(shape=(1, 5))

sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forwad propagation(tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

print('x: {}\n{}'.format(x.shape, x.numpy()))
print('sigmoid(Tensorflow): {}\n{}'.format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print('tanh(Tensorflow): {}\n{}'.format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print('relu(Tensorflow): {}\n{}'.format(y_relu_tf.shape, y_relu_tf.numpy()))

x: (1, 5)
[[-0.8757808   0.3356369  -0.35219625 -0.30314562 -0.03882965]]
sigmoid(Tensorflow): (1, 5)
[[0.29405284 0.5831303  0.41284993 0.42478868 0.49029383]]
tanh(Tensorflow): (1, 5)
[[-0.70429933  0.32357663 -0.33832183 -0.29418862 -0.03881015]]
relu(Tensorflow): (1, 5)
[[0.        0.3356369 0.        0.        0.       ]]


In [16]:
# forwad propagation(manual)
y_sigmoid_man = 1 / (1+tf.math.exp(-x))
y_tanh_man = (tf.math.exp(x) - tf.math.exp(-x)) / (tf.math.exp(x) + tf.math.exp(-x))
y_relu_man = tf.math.maximum(x, 0)

print('x: {}\n{}'.format(x.shape, x.numpy()))
print('sigmoid(manual): {}\n{}'.format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))
print('tanh(manual): {}\n{}'.format(y_tanh_man.shape, y_tanh_man.numpy()))
print('relu(manual): {}\n{}'.format(y_relu_man.shape, y_relu_man.numpy()))

x: (1, 5)
[[-0.8757808   0.3356369  -0.35219625 -0.30314562 -0.03882965]]
sigmoid(manual): (1, 5)
[[0.29405284 0.5831303  0.41284993 0.42478868 0.49029383]]
tanh(manual): (1, 5)
[[-0.70429933  0.32357663 -0.33832183 -0.29418865 -0.03881014]]
relu(manual): (1, 5)
[[0.        0.3356369 0.        0.        0.       ]]


In [9]:
# Activation in Dense Layer
from tensorflow.keras.layers import Dense
tf.random.set_seed(10)
x = tf.random.normal(shape=(1, 5))

# imp. Artifical neurons
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print('AN with sigmoid: {}\n{}'.format(y_sigmoid.shape, y_sigmoid.numpy()))
print('AN with thah: {}\n{}'.format(y_tanh.shape, y_tanh.numpy()))
print('AN with relu: {}\n{}'.format(y_relu.shape, y_relu.numpy()))

AN with sigmoid: (1, 1)
[[0.498436]]
AN with thah: (1, 1)
[[0.32123712]]
AN with relu: (1, 1)
[[0.]]


In [11]:
# forward propagation(manual)
W, b = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + b
a = 1 / (1 + tf.exp(-z))

print('Activation value(Tensorflow): {}\n{}'.format(y_sigmoid.shape, y_sigmoid.numpy()))
print('Activation value(Manual): {}\n{}'.format(a.shape, a.numpy()))

Activation value(Tensorflow): (1, 1)
[[0.498436]]
Activation value(Manual): (1, 1)
[[0.498436]]


In [17]:
# Minibatches, Shapes of Dense Layers
N, n_features = 8, 10
tf.random.set_seed(10)
x = tf.random.normal(shape=(N, n_features))

dense = Dense(units=1, activation='relu')
y = dense(x)
W, b = dense.get_weights()

print('Shape of x: ', x.shape)
print('Shape of W: ', W.shape)
print('Shape of b: ', b.shape)

Shape of x:  (8, 10)
Shape of W:  (10, 1)
Shape of b:  (1,)


In [18]:
# Output Calculations
N, n_features = 8, 10
tf.random.set_seed(10)
x = tf.random.normal(shape=(N, n_features))

dense = Dense(units=1, activation='sigmoid')
y_tf = dense(x)
W, b = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + b
y_man = 1 / (1+tf.math.exp(-y_man))

print('Output(Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('Output(Manual): {}\n{}\n'.format(y_man.shape, y_man.numpy()))

Output(Tensorflow): (8, 1)
[[0.46854383]
 [0.5895974 ]
 [0.10466997]
 [0.8744324 ]
 [0.7818612 ]
 [0.47610277]
 [0.33888915]
 [0.7424137 ]]

Output(Manual): (8, 1)
[[0.46854383]
 [0.5895974 ]
 [0.10466997]
 [0.8744324 ]
 [0.7818612 ]
 [0.47610277]
 [0.33888915]
 [0.7424137 ]]

