# 2.1 Logistic Regression
- Parameter C를 조정해 과대적합 혹은 과소적합 문제를 해결
- C (cost function)값이 크면 (높은 cost) -> 훈련을 더 복잡하게 -> 약한 규제 -> 과대적합
- C 값이 작으면 (낮은 cost) -> 훈련을 덜 복잡하게 -> 강한 규제 -> 과소적합

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

C:\Users\admin\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\admin\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
iris=datasets.load_iris()

In [4]:
# data 분할 (이항분류를 위해)
X=iris.data[50:,:]
y=iris.target[50:]
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3, random_state=58)

In [5]:
X_train.shape

(70, 4)

In [6]:
# Modeling
logreg=LogisticRegression().fit(X_train,y_train)

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [7]:
logreg.score(X_train,y_train)

0.9857142857142858

In [8]:
logreg.score(X_test,y_test)

0.9333333333333333

In [23]:
# parameter tuning
logreg001=LogisticRegression(solver='lbfgs', C=0.01).fit(X_train,y_train)
logreg001

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
# parameter tuning
logreg100=LogisticRegression(solver='lbfgs', C=100).fit(X_train,y_train)
logreg100

LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
# 결과 비교 
print("train set score",logreg001.score(X_train,y_train))
print("test set score", logreg001.score(X_test,y_test))

train set score 0.9142857142857143
test set score 0.9


In [26]:
# 결과 비교 
print("train set score",logreg100.score(X_train,y_train))
print("test set score", logreg100.score(X_test,y_test))

train set score 0.9857142857142858
test set score 0.9


## 역으로 계산해서 predict_proba()와 비교

In [16]:
logreg.coef_ # iris data의 4개의 feature에 대한 회귀 계수 

array([[-1.51169047, -1.34432386,  2.12855352,  2.31350688]])

In [17]:
logreg.coef_[0][0]*X_test[:,0]

array([ -7.55845235, -10.12832615,  -9.97715711,  -8.31429759,
       -10.43066425,  -8.61663568,  -9.07014282, -10.12832615,
        -9.52364996,  -9.82598806,  -8.91897378,  -8.76780473,
       -11.94235472,  -9.52364996,  -7.40728331,  -8.31429759,
        -9.37248092,  -9.82598806,  -8.76780473,  -9.52364996,
        -8.46546664, -10.88417139, -10.2794952 , -10.12832615,
        -9.52364996,  -9.67481901,  -9.52364996,  -8.46546664,
        -7.40728331, -11.03534044])

In [20]:
ans= logreg.coef_[0][0]*X_test[:,np.newaxis,0]+logreg.coef_[0][1]*X_test[:,np.newaxis,1]+logreg.coef_[0][2]*X_test[:,np.newaxis,2]+logreg.coef_[0][3]*X_test[:,np.newaxis,3]+logreg.intercept_

In [21]:
odds=np.exp(ans)

In [22]:
finalvalues=odds/(1+odds)
finalvalues

array([[0.09269978],
       [0.8861842 ],
       [0.11453478],
       [0.08948304],
       [0.85231528],
       [0.12989158],
       [0.75341865],
       [0.77899217],
       [0.97408625],
       [0.21468183],
       [0.54788173],
       [0.12553058],
       [0.55737797],
       [0.84469431],
       [0.85506797],
       [0.13287694],
       [0.56864822],
       [0.59540825],
       [0.08904543],
       [0.9175505 ],
       [0.39696417],
       [0.68593486],
       [0.17421001],
       [0.06539804],
       [0.5174137 ],
       [0.83987531],
       [0.51181516],
       [0.12471663],
       [0.09411707],
       [0.84182584]])